version: "3"

services:
  voyager:
    container_name: voyager
    image: registry.huc.knaw.nl/vicd/voyager:latest
    env_file:
      - .env
    volumes:
      - ./files:/app/files
    ports:
      - "8000:8000"
